# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: admin
ansible_password: admin
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false
act_username: admin
act_password: admin

digital_twin:

  # Targeted Digital Twin environment.
  environment: act

  # Settings for Digital Twin fabric devices.
  fabric:
    act_os_version: 4.33.2F
    act_username: admin
    act_password: admin
    act_internet_access: true
    act_ensure_eapi_access: true
  use_default_interfaces_of_digital_twin_platform: false
