---
- name: Update Arista fabric configuration
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - ansible.scm
  vars:
    artifacts_repository: https://github.com/natedoot/avd-aap
    artifacts_branch: main
    artifacts_folder: documentation
    changes_name: "Configuration changes by Ansible Automation Platform"
    changes_description: |
      Triggered by commit: AAP Job ID
      Job: JobID HERE
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    cv_token: "{{ lookup('env', 'CV_TOKEN') }}"

  tasks:
    - name: Retrieve latest artifacts
      delegate_to: localhost
      run_once: true
      git_retrieve:
        origin:
          url: "{{ artifacts_repository }}"
        branch:
          name: "{{ artifacts_branch }}"
          duplicate_detection: false
      register: repository

    - name: Generate AVD structured configurations
      import_role:
        name: eos_designs

    - name: Generate EOS intended configuration and device documentation
      import_role:
        name: eos_cli_config_gen
    
    - name: Deploy configurations and tags to CloudVision
      import_role:
        name: cv_deploy
      vars:
        cv_server: www.cv-prod-us-central1-b.arista.io

    - name: Publish artifacts
      #when: eos_config.changed
      run_once: true
      delegate_to: localhost
      git_publish:
        commit:
          message: |
            {{ changes_name }}

            {{ changes_description }}
            
        token: "{{ github_token }}"
        path: "{{ repository['path'] }}"
        include: ["{{ artifacts_folder }}"]
