---
- name: Update Arista fabric configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - ansible.scm
  vars:
    fabric_dir_name: "{{ fabric_name }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    cv_token: "{{ lookup('env', 'CV_TOKEN') }}"

  tasks:
    - name: Retrieve a repository from a distant location and make it available to the local EE
      ansible.scm.git_retrieve:
        origin:
          url: "https://github.com/natedoot/avd-aap.git"
        parent_directory: /tmp/
        branch:
          name: main
          duplicate_detection: no
      register: repository
      delegate_to: localhost
      run_once: true

    - name: Generate intended variables
      include_role:
        name: eos_designs

    - name: Generate device intended config and documentation
      include_role:
        name: eos_cli_config_gen

    - name: Check generated AVD paths
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /runner/project/intended/structured_configs
        - /runner/project/intended/configs
        - /runner/project/documentation/DC1_FABRIC
      delegate_to: localhost
      run_once: true
      register: avd_paths

    - name: Show generated AVD path checks
      ansible.builtin.debug:
        var: avd_paths.results
      run_once: true

    - name: Copy generated artifacts into repository
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
        force: true
        remote_src: true
      delegate_to: localhost
      run_once: true
      loop:
        - dest: "{{ repository.path }}/intended/"
          src: /runner/project/intended/structured_configs
        - dest: "{{ repository.path }}/intended/"
          src: /runner/project/intended/configs
        - dest: "{{ repository.path }}/documentation/"
          src: /runner/project/documentation/DC1_FABRIC

    - name: Publish the changes
      ansible.scm.git_publish:
        path: "{{ repository['path'] }}"
        token: "{{ github_token }}"
        user:
          name: "natedoot"
          email: "nate.shaw@arista.com"
      delegate_to: localhost
      run_once: true

    - name: Provision CV with AVD configuration
      include_role:
        name: cv_deploy
      vars:
        cv_server: www.cv-prod-us-central1-b.arista.io
        cv_token: "{{ cv_token }}"
