---
- name: Test Arista fabric state
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - ansible.scm

  vars:
    artifacts_repository: "https://github.com/natedoot/avd-aap.git"
    artifacts_branch: "main"
    artifacts_folder: "artifacts"
    anta_folder: "anta"
    anta_root_dir: "{{ repository.path }}/{{ artifacts_folder }}"
    changes_name: "Update ANTA validation results from AAP"
    changes_description: "Job ID: {{ awx_job_id }}"
    github_pat: "{{ lookup('env', 'GITHUB_TOKEN') }}"

  tasks:
    - name: Retrieve latest artifacts repository
      delegate_to: localhost
      run_once: true
      ansible.scm.git_retrieve:
        origin:
          url: "{{ artifacts_repository }}"
        branch:
          name: "{{ artifacts_branch }}"
          duplicate_detection: false
      register: repository

    - name: Remove previous ANTA reports and logs
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}/reports"
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}/logs"

    - name: Ensure ANTA artifact directories exist
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ repository.path }}/{{ artifacts_folder }}"
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}"
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}/avd_catalogs"
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}/reports"
        - "{{ repository.path }}/{{ artifacts_folder }}/{{ anta_folder }}/logs"

    - name: Test network states
      ansible.builtin.import_role:
        name: anta_runner
      vars:
        root_dir: "{{ anta_root_dir }}"

    - name: Publish ANTA artifacts
      run_once: true
      delegate_to: localhost
      ansible.scm.git_publish:
        commit:
          message: |
            {{ changes_name }}

            {{ changes_description }}
        token: "{{ github_pat }}"
        path: "{{ repository.path }}"
        include:
          - "{{ artifacts_folder }}/{{ anta_folder }}"
